/* $NetBSD$ */

/*
 * System call numbers.
 *
 * DO NOT EDIT-- this file is automatically generated.
 * created from	NetBSD
 */

#ifndef _CLOUDABI64_SYS_SYSCALL_H_
#define	_CLOUDABI64_SYS_SYSCALL_H_

#define	CLOUDABI64_SYS_MAXSYSARGS	8

/* syscall: "clock_res_get" ret: "cloudabi_timestamp_t" args: "cloudabi_clockid_t" */
#define	CLOUDABI64_SYS_clock_res_get	0

/* syscall: "clock_time_get" ret: "cloudabi_timestamp_t" args: "cloudabi_clockid_t" "cloudabi_timestamp_t" */
#define	CLOUDABI64_SYS_clock_time_get	1

/* syscall: "condvar_signal" ret: "void" args: "cloudabi_condvar_t *" "cloudabi_mflags_t" "cloudabi_nthreads_t" */
#define	CLOUDABI64_SYS_condvar_signal	2

/* syscall: "fd_close" ret: "void" args: "cloudabi_fd_t" */
#define	CLOUDABI64_SYS_fd_close	3

/* syscall: "fd_create1" ret: "cloudabi_fd_t" args: "cloudabi_filetype_t" */
#define	CLOUDABI64_SYS_fd_create1	4

/* syscall: "fd_create2" ret: "void" args: "cloudabi_filetype_t" */
#define	CLOUDABI64_SYS_fd_create2	5

/* syscall: "fd_datasync" ret: "void" args: "cloudabi_fd_t" */
#define	CLOUDABI64_SYS_fd_datasync	6

/* syscall: "fd_dup" ret: "cloudabi_fd_t" args: "cloudabi_fd_t" */
#define	CLOUDABI64_SYS_fd_dup	7

/* syscall: "fd_pread" ret: "cloudabi64_size_t" args: "cloudabi_fd_t" "const cloudabi64_iovec_t *" "cloudabi64_size_t" "cloudabi_filesize_t" */
#define	CLOUDABI64_SYS_fd_pread	8

/* syscall: "fd_pwrite" ret: "cloudabi64_size_t" args: "cloudabi_fd_t" "const cloudabi64_ciovec_t *" "cloudabi64_size_t" "cloudabi_filesize_t" */
#define	CLOUDABI64_SYS_fd_pwrite	9

/* syscall: "fd_read" ret: "cloudabi64_size_t" args: "cloudabi_fd_t" "const cloudabi64_iovec_t *" "cloudabi64_size_t" */
#define	CLOUDABI64_SYS_fd_read	10

/* syscall: "fd_replace" ret: "void" args: "cloudabi_fd_t" "cloudabi_fd_t" */
#define	CLOUDABI64_SYS_fd_replace	11

/* syscall: "fd_seek" ret: "cloudabi_filesize_t" args: "cloudabi_fd_t" "cloudabi_filedelta_t" "cloudabi_whence_t" */
#define	CLOUDABI64_SYS_fd_seek	12

/* syscall: "fd_stat_get" ret: "void" args: "cloudabi_fd_t" "cloudabi_fdstat_t *" */
#define	CLOUDABI64_SYS_fd_stat_get	13

/* syscall: "fd_stat_put" ret: "void" args: "cloudabi_fd_t" "const cloudabi_fdstat_t *" "cloudabi_fdsflags_t" */
#define	CLOUDABI64_SYS_fd_stat_put	14

/* syscall: "fd_sync" ret: "void" args: "cloudabi_fd_t" */
#define	CLOUDABI64_SYS_fd_sync	15

/* syscall: "fd_write" ret: "cloudabi64_size_t" args: "cloudabi_fd_t" "const cloudabi64_ciovec_t *" "cloudabi64_size_t" */
#define	CLOUDABI64_SYS_fd_write	16

/* syscall: "file_advise" ret: "void" args: "cloudabi_fd_t" "cloudabi_filesize_t" "cloudabi_filesize_t" "cloudabi_advice_t" */
#define	CLOUDABI64_SYS_file_advise	17

/* syscall: "file_allocate" ret: "void" args: "cloudabi_fd_t" "cloudabi_filesize_t" "cloudabi_filesize_t" */
#define	CLOUDABI64_SYS_file_allocate	18

/* syscall: "file_create" ret: "void" args: "cloudabi_fd_t" "const char *" "size_t" "cloudabi_filetype_t" */
#define	CLOUDABI64_SYS_file_create	19

/* syscall: "file_link" ret: "void" args: "cloudabi_lookup_t" "const char *" "size_t" "cloudabi_fd_t" "const char *" "size_t" */
#define	CLOUDABI64_SYS_file_link	20

/* syscall: "file_open" ret: "cloudabi_fd_t" args: "cloudabi_lookup_t" "const char *" "size_t" "cloudabi_oflags_t" "const cloudabi_fdstat_t *" */
#define	CLOUDABI64_SYS_file_open	21

/* syscall: "file_readdir" ret: "size_t" args: "cloudabi_fd_t" "void *" "size_t" "cloudabi_dircookie_t" */
#define	CLOUDABI64_SYS_file_readdir	22

/* syscall: "file_readlink" ret: "size_t" args: "cloudabi_fd_t" "const char *" "size_t" "void *" "size_t" */
#define	CLOUDABI64_SYS_file_readlink	23

/* syscall: "file_rename" ret: "void" args: "cloudabi_fd_t" "const char *" "size_t" "cloudabi_fd_t" "const char *" "size_t" */
#define	CLOUDABI64_SYS_file_rename	24

/* syscall: "file_stat_fget" ret: "void" args: "cloudabi_fd_t" "cloudabi_filestat_t *" */
#define	CLOUDABI64_SYS_file_stat_fget	25

/* syscall: "file_stat_fput" ret: "void" args: "cloudabi_fd_t" "const cloudabi_filestat_t *" "cloudabi_fsflags_t" */
#define	CLOUDABI64_SYS_file_stat_fput	26

/* syscall: "file_stat_get" ret: "void" args: "cloudabi_lookup_t" "const char *" "size_t" "cloudabi_filestat_t *" */
#define	CLOUDABI64_SYS_file_stat_get	27

/* syscall: "file_stat_put" ret: "void" args: "cloudabi_lookup_t" "const char *" "size_t" "const cloudabi_filestat_t *" "cloudabi_fsflags_t" */
#define	CLOUDABI64_SYS_file_stat_put	28

/* syscall: "file_symlink" ret: "void" args: "const char *" "size_t" "cloudabi_fd_t" "const char *" "size_t" */
#define	CLOUDABI64_SYS_file_symlink	29

/* syscall: "file_unlink" ret: "void" args: "cloudabi_fd_t" "const char *" "size_t" "cloudabi_ulflags_t" */
#define	CLOUDABI64_SYS_file_unlink	30

/* syscall: "lock_unlock" ret: "void" args: "cloudabi_lock_t *" "cloudabi_mflags_t" */
#define	CLOUDABI64_SYS_lock_unlock	31

/* syscall: "mem_advise" ret: "void" args: "void *" "size_t" "cloudabi_advice_t" */
#define	CLOUDABI64_SYS_mem_advise	32

/* syscall: "mem_lock" ret: "void" args: "const void *" "size_t" */
#define	CLOUDABI64_SYS_mem_lock	33

/* syscall: "mem_map" ret: "void" args: "void *" "size_t" "cloudabi_mprot_t" "cloudabi_mflags_t" "cloudabi_fd_t" "cloudabi_filesize_t" */
#define	CLOUDABI64_SYS_mem_map	34

/* syscall: "mem_protect" ret: "void" args: "void *" "size_t" "cloudabi_mprot_t" */
#define	CLOUDABI64_SYS_mem_protect	35

/* syscall: "mem_sync" ret: "void" args: "void *" "size_t" "cloudabi_msflags_t" */
#define	CLOUDABI64_SYS_mem_sync	36

/* syscall: "mem_unlock" ret: "void" args: "const void *" "size_t" */
#define	CLOUDABI64_SYS_mem_unlock	37

/* syscall: "mem_unmap" ret: "void" args: "void *" "size_t" */
#define	CLOUDABI64_SYS_mem_unmap	38

/* syscall: "poll" ret: "cloudabi64_size_t" args: "const cloudabi64_subscription_t *" "cloudabi64_event_t *" "cloudabi64_size_t" */
#define	CLOUDABI64_SYS_poll	39

/* syscall: "proc_exec" ret: "void" args: "cloudabi_fd_t" "const void *" "size_t" "const cloudabi_fd_t *" "size_t" */
#define	CLOUDABI64_SYS_proc_exec	40

/* syscall: "proc_exit" ret: "void" args: "cloudabi_exitcode_t" */
#define	CLOUDABI64_SYS_proc_exit	41

/* syscall: "proc_fork" ret: "cloudabi_fd_t" args: */
#define	CLOUDABI64_SYS_proc_fork	42

/* syscall: "proc_raise" ret: "void" args: "cloudabi_signal_t" */
#define	CLOUDABI64_SYS_proc_raise	43

/* syscall: "random_get" ret: "void" args: "void *" "size_t" */
#define	CLOUDABI64_SYS_random_get	44

/* syscall: "sock_accept" ret: "cloudabi_fd_t" args: "cloudabi_fd_t" "cloudabi_sockstat_t *" */
#define	CLOUDABI64_SYS_sock_accept	45

/* syscall: "sock_bind" ret: "void" args: "cloudabi_fd_t" "cloudabi_fd_t" "const char *" "size_t" */
#define	CLOUDABI64_SYS_sock_bind	46

/* syscall: "sock_connect" ret: "void" args: "cloudabi_fd_t" "cloudabi_fd_t" "const char *" "size_t" */
#define	CLOUDABI64_SYS_sock_connect	47

/* syscall: "sock_listen" ret: "void" args: "cloudabi_fd_t" "cloudabi_backlog_t" */
#define	CLOUDABI64_SYS_sock_listen	48

/* syscall: "sock_recv" ret: "cloudabi64_size_t" args: "cloudabi_fd_t" "const cloudabi64_recv_in_t *" "cloudabi64_recv_out_t *" */
#define	CLOUDABI64_SYS_sock_recv	49

/* syscall: "sock_send" ret: "cloudabi64_size_t" args: "cloudabi_fd_t" "const cloudabi64_send_in_t *" "cloudabi64_send_out_t *" */
#define	CLOUDABI64_SYS_sock_send	50

/* syscall: "sock_shutdown" ret: "void" args: "cloudabi_fd_t" "cloudabi_sdflags_t" */
#define	CLOUDABI64_SYS_sock_shutdown	51

/* syscall: "sock_stat_get" ret: "void" args: "cloudabi_fd_t" "cloudabi_sockstat_t *" "cloudabi_ssflags_t" */
#define	CLOUDABI64_SYS_sock_stat_get	52

/* syscall: "thread_create" ret: "cloudabi_tid_t" args: "cloudabi64_threadattr_t *" */
#define	CLOUDABI64_SYS_thread_create	53

/* syscall: "thread_exit" ret: "void" args: "cloudabi_lock_t *" "cloudabi_mflags_t" */
#define	CLOUDABI64_SYS_thread_exit	54

/* syscall: "thread_tcb_set" ret: "void" args: "void *" */
#define	CLOUDABI64_SYS_thread_tcb_set	55

/* syscall: "thread_yield" ret: "void" args: */
#define	CLOUDABI64_SYS_thread_yield	56

/* syscall: "poll_fd" ret: "cloudabi64_size_t" args: "cloudabi_fd_t" "const cloudabi64_subscription_t *" "cloudabi64_size_t" "cloudabi64_event_t *" "cloudabi64_size_t" "const cloudabi64_subscription_t *" */
#define	CLOUDABI64_SYS_poll_fd	57

#define	CLOUDABI64_SYS_MAXSYSCALL	58
#define	CLOUDABI64_SYS_NSYSENT	512
#endif /* _CLOUDABI64_SYS_SYSCALL_H_ */
