/* $NetBSD$ */

/*
 * System call argument lists.
 *
 * DO NOT EDIT-- this file is automatically generated.
 * created from	NetBSD
 */

#ifndef _CLOUDABI64_SYS_SYSCALLARGS_H_
#define	_CLOUDABI64_SYS_SYSCALLARGS_H_

#define	CLOUDABI64_SYS_MAXSYSARGS	8

#undef	syscallarg
#define	syscallarg(x)							\
	union {								\
		register_t pad;						\
		struct { x datum; } le;					\
		struct { /* LINTED zero array dimension */		\
			int8_t pad[  /* CONSTCOND */			\
				(sizeof (register_t) < sizeof (x))	\
				? 0					\
				: sizeof (register_t) - sizeof (x)];	\
			x datum;					\
		} be;							\
	}

#undef check_syscall_args
#define check_syscall_args(call) /*LINTED*/ \
	typedef char call##_check_args[sizeof (struct call##_args) \
		<= CLOUDABI64_SYS_MAXSYSARGS * sizeof (register_t) ? 1 : -1];

struct cloudabi_sys_clock_res_get_args {
	syscallarg(cloudabi_clockid_t) clock_id;
};
check_syscall_args(cloudabi_sys_clock_res_get)

struct cloudabi_sys_clock_time_get_args {
	syscallarg(cloudabi_clockid_t) clock_id;
	syscallarg(cloudabi_timestamp_t) precision;
};
check_syscall_args(cloudabi_sys_clock_time_get)

struct cloudabi_sys_condvar_signal_args {
	syscallarg(cloudabi_condvar_t *) condvar;
	syscallarg(cloudabi_nthreads_t) nwaiters;
};
check_syscall_args(cloudabi_sys_condvar_signal)

struct cloudabi_sys_fd_close_args {
	syscallarg(cloudabi_fd_t) fd;
};
check_syscall_args(cloudabi_sys_fd_close)

struct cloudabi_sys_fd_create1_args {
	syscallarg(cloudabi_filetype_t) type;
};
check_syscall_args(cloudabi_sys_fd_create1)

struct cloudabi_sys_fd_create2_args {
	syscallarg(cloudabi_filetype_t) type;
};
check_syscall_args(cloudabi_sys_fd_create2)

struct cloudabi_sys_fd_datasync_args {
	syscallarg(cloudabi_fd_t) fd;
};
check_syscall_args(cloudabi_sys_fd_datasync)

struct cloudabi_sys_fd_dup_args {
	syscallarg(cloudabi_fd_t) from;
};
check_syscall_args(cloudabi_sys_fd_dup)

struct cloudabi64_sys_fd_pread_args {
	syscallarg(cloudabi_fd_t) fd;
	syscallarg(const cloudabi64_iovec_t *) iov;
	syscallarg(cloudabi64_size_t) iovcnt;
	syscallarg(cloudabi_filesize_t) offset;
};
check_syscall_args(cloudabi64_sys_fd_pread)

struct cloudabi64_sys_fd_pwrite_args {
	syscallarg(cloudabi_fd_t) fd;
	syscallarg(const cloudabi64_ciovec_t *) iov;
	syscallarg(cloudabi64_size_t) iovcnt;
	syscallarg(cloudabi_filesize_t) offset;
};
check_syscall_args(cloudabi64_sys_fd_pwrite)

struct cloudabi64_sys_fd_read_args {
	syscallarg(cloudabi_fd_t) fd;
	syscallarg(const cloudabi64_iovec_t *) iov;
	syscallarg(cloudabi64_size_t) iovcnt;
};
check_syscall_args(cloudabi64_sys_fd_read)

struct cloudabi_sys_fd_replace_args {
	syscallarg(cloudabi_fd_t) from;
	syscallarg(cloudabi_fd_t) to;
};
check_syscall_args(cloudabi_sys_fd_replace)

struct cloudabi_sys_fd_seek_args {
	syscallarg(cloudabi_fd_t) fd;
	syscallarg(cloudabi_filedelta_t) offset;
	syscallarg(cloudabi_whence_t) whence;
};
check_syscall_args(cloudabi_sys_fd_seek)

struct cloudabi_sys_fd_stat_get_args {
	syscallarg(cloudabi_fd_t) fd;
	syscallarg(cloudabi_fdstat_t *) buf;
};
check_syscall_args(cloudabi_sys_fd_stat_get)

struct cloudabi_sys_fd_stat_put_args {
	syscallarg(cloudabi_fd_t) fd;
	syscallarg(const cloudabi_fdstat_t *) buf;
	syscallarg(cloudabi_fdsflags_t) flags;
};
check_syscall_args(cloudabi_sys_fd_stat_put)

struct cloudabi_sys_fd_sync_args {
	syscallarg(cloudabi_fd_t) fd;
};
check_syscall_args(cloudabi_sys_fd_sync)

struct cloudabi64_sys_fd_write_args {
	syscallarg(cloudabi_fd_t) fd;
	syscallarg(const cloudabi64_ciovec_t *) iov;
	syscallarg(cloudabi64_size_t) iovcnt;
};
check_syscall_args(cloudabi64_sys_fd_write)

struct cloudabi_sys_file_advise_args {
	syscallarg(cloudabi_fd_t) fd;
	syscallarg(cloudabi_filesize_t) offset;
	syscallarg(cloudabi_filesize_t) len;
	syscallarg(cloudabi_advice_t) advice;
};
check_syscall_args(cloudabi_sys_file_advise)

struct cloudabi_sys_file_allocate_args {
	syscallarg(cloudabi_fd_t) fd;
	syscallarg(cloudabi_filesize_t) offset;
	syscallarg(cloudabi_filesize_t) len;
};
check_syscall_args(cloudabi_sys_file_allocate)

struct cloudabi_sys_file_create_args {
	syscallarg(cloudabi_fd_t) fd;
	syscallarg(const char *) path;
	syscallarg(size_t) pathlen;
	syscallarg(cloudabi_filetype_t) type;
};
check_syscall_args(cloudabi_sys_file_create)

struct cloudabi_sys_file_link_args {
	syscallarg(cloudabi_lookup_t) fd1;
	syscallarg(const char *) path1;
	syscallarg(size_t) path1len;
	syscallarg(cloudabi_fd_t) fd2;
	syscallarg(const char *) path2;
	syscallarg(size_t) path2len;
};
check_syscall_args(cloudabi_sys_file_link)

struct cloudabi_sys_file_open_args {
	syscallarg(cloudabi_lookup_t) fd;
	syscallarg(const char *) path;
	syscallarg(size_t) pathlen;
	syscallarg(cloudabi_oflags_t) oflags;
	syscallarg(const cloudabi_fdstat_t *) fds;
};
check_syscall_args(cloudabi_sys_file_open)

struct cloudabi_sys_file_readdir_args {
	syscallarg(cloudabi_fd_t) fd;
	syscallarg(void *) buf;
	syscallarg(size_t) nbyte;
	syscallarg(cloudabi_dircookie_t) cookie;
};
check_syscall_args(cloudabi_sys_file_readdir)

struct cloudabi_sys_file_readlink_args {
	syscallarg(cloudabi_fd_t) fd;
	syscallarg(const char *) path;
	syscallarg(size_t) pathlen;
	syscallarg(void *) buf;
	syscallarg(size_t) bufsize;
};
check_syscall_args(cloudabi_sys_file_readlink)

struct cloudabi_sys_file_rename_args {
	syscallarg(cloudabi_fd_t) oldfd;
	syscallarg(const char *) old;
	syscallarg(size_t) oldlen;
	syscallarg(cloudabi_fd_t) newfd;
	syscallarg(const char *) new;
	syscallarg(size_t) newlen;
};
check_syscall_args(cloudabi_sys_file_rename)

struct cloudabi_sys_file_stat_fget_args {
	syscallarg(cloudabi_fd_t) fd;
	syscallarg(cloudabi_filestat_t *) buf;
};
check_syscall_args(cloudabi_sys_file_stat_fget)

struct cloudabi_sys_file_stat_fput_args {
	syscallarg(cloudabi_fd_t) fd;
	syscallarg(const cloudabi_filestat_t *) buf;
	syscallarg(cloudabi_fsflags_t) flags;
};
check_syscall_args(cloudabi_sys_file_stat_fput)

struct cloudabi_sys_file_stat_get_args {
	syscallarg(cloudabi_lookup_t) fd;
	syscallarg(const char *) path;
	syscallarg(size_t) pathlen;
	syscallarg(cloudabi_filestat_t *) buf;
};
check_syscall_args(cloudabi_sys_file_stat_get)

struct cloudabi_sys_file_stat_put_args {
	syscallarg(cloudabi_lookup_t) fd;
	syscallarg(const char *) path;
	syscallarg(size_t) pathlen;
	syscallarg(const cloudabi_filestat_t *) buf;
	syscallarg(cloudabi_fsflags_t) flags;
};
check_syscall_args(cloudabi_sys_file_stat_put)

struct cloudabi_sys_file_symlink_args {
	syscallarg(const char *) path1;
	syscallarg(size_t) path1len;
	syscallarg(cloudabi_fd_t) fd;
	syscallarg(const char *) path2;
	syscallarg(size_t) path2len;
};
check_syscall_args(cloudabi_sys_file_symlink)

struct cloudabi_sys_file_unlink_args {
	syscallarg(cloudabi_fd_t) fd;
	syscallarg(const char *) path;
	syscallarg(size_t) pathlen;
	syscallarg(cloudabi_ulflags_t) flag;
};
check_syscall_args(cloudabi_sys_file_unlink)

struct cloudabi_sys_lock_unlock_args {
	syscallarg(cloudabi_lock_t *) lock;
};
check_syscall_args(cloudabi_sys_lock_unlock)

struct cloudabi_sys_mem_advise_args {
	syscallarg(void *) addr;
	syscallarg(size_t) len;
	syscallarg(cloudabi_advice_t) advice;
};
check_syscall_args(cloudabi_sys_mem_advise)

struct cloudabi_sys_mem_lock_args {
	syscallarg(const void *) addr;
	syscallarg(size_t) len;
};
check_syscall_args(cloudabi_sys_mem_lock)

struct cloudabi_sys_mem_map_args {
	syscallarg(void *) addr;
	syscallarg(size_t) len;
	syscallarg(cloudabi_mprot_t) prot;
	syscallarg(cloudabi_mflags_t) flags;
	syscallarg(cloudabi_fd_t) fd;
	syscallarg(cloudabi_filesize_t) off;
};
check_syscall_args(cloudabi_sys_mem_map)

struct cloudabi_sys_mem_protect_args {
	syscallarg(void *) addr;
	syscallarg(size_t) len;
	syscallarg(cloudabi_mprot_t) prot;
};
check_syscall_args(cloudabi_sys_mem_protect)

struct cloudabi_sys_mem_sync_args {
	syscallarg(void *) addr;
	syscallarg(size_t) len;
	syscallarg(cloudabi_msflags_t) flags;
};
check_syscall_args(cloudabi_sys_mem_sync)

struct cloudabi_sys_mem_unlock_args {
	syscallarg(const void *) addr;
	syscallarg(size_t) len;
};
check_syscall_args(cloudabi_sys_mem_unlock)

struct cloudabi_sys_mem_unmap_args {
	syscallarg(void *) addr;
	syscallarg(size_t) len;
};
check_syscall_args(cloudabi_sys_mem_unmap)

struct cloudabi64_sys_poll_args {
	syscallarg(cloudabi_fd_t) fd;
	syscallarg(const cloudabi64_event_t *) in;
	syscallarg(cloudabi64_size_t) nin;
	syscallarg(cloudabi64_event_t *) out;
	syscallarg(cloudabi64_size_t) nout;
};
check_syscall_args(cloudabi64_sys_poll)

struct cloudabi64_sys_proc_exec_args {
	syscallarg(cloudabi_fd_t) fd;
	syscallarg(const cloudabi64_ciovec_t *) iov;
	syscallarg(cloudabi64_size_t) iovcnt;
	syscallarg(const cloudabi_fd_t *) fds;
	syscallarg(cloudabi64_size_t) fdscnt;
};
check_syscall_args(cloudabi64_sys_proc_exec)

struct cloudabi_sys_proc_exit_args {
	syscallarg(cloudabi_exitcode_t) rval;
};
check_syscall_args(cloudabi_sys_proc_exit)

struct cloudabi_sys_proc_raise_args {
	syscallarg(cloudabi_signal_t) sig;
};
check_syscall_args(cloudabi_sys_proc_raise)

struct cloudabi_sys_random_get_args {
	syscallarg(void *) buf;
	syscallarg(size_t) nbyte;
};
check_syscall_args(cloudabi_sys_random_get)

struct cloudabi_sys_sock_accept_args {
	syscallarg(cloudabi_fd_t) s;
	syscallarg(cloudabi_sockstat_t *) buf;
};
check_syscall_args(cloudabi_sys_sock_accept)

struct cloudabi_sys_sock_bind_args {
	syscallarg(cloudabi_fd_t) s;
	syscallarg(cloudabi_fd_t) fd;
	syscallarg(const char *) path;
	syscallarg(size_t) pathlen;
};
check_syscall_args(cloudabi_sys_sock_bind)

struct cloudabi_sys_sock_connect_args {
	syscallarg(cloudabi_fd_t) s;
	syscallarg(cloudabi_fd_t) fd;
	syscallarg(const char *) path;
	syscallarg(size_t) pathlen;
};
check_syscall_args(cloudabi_sys_sock_connect)

struct cloudabi_sys_sock_listen_args {
	syscallarg(cloudabi_fd_t) s;
	syscallarg(cloudabi_backlog_t) backlog;
};
check_syscall_args(cloudabi_sys_sock_listen)

struct cloudabi64_sys_sock_recv_args {
	syscallarg(cloudabi_fd_t) s;
	syscallarg(const cloudabi64_recv_in_t *) in;
	syscallarg(cloudabi64_recv_out_t *) out;
};
check_syscall_args(cloudabi64_sys_sock_recv)

struct cloudabi64_sys_sock_send_args {
	syscallarg(cloudabi_fd_t) s;
	syscallarg(const cloudabi64_send_in_t *) in;
	syscallarg(cloudabi64_send_out_t *) out;
};
check_syscall_args(cloudabi64_sys_sock_send)

struct cloudabi_sys_sock_shutdown_args {
	syscallarg(cloudabi_fd_t) fd;
	syscallarg(cloudabi_sdflags_t) how;
};
check_syscall_args(cloudabi_sys_sock_shutdown)

struct cloudabi_sys_sock_stat_get_args {
	syscallarg(cloudabi_fd_t) fd;
	syscallarg(cloudabi_sockstat_t *) buf;
	syscallarg(cloudabi_ssflags_t) flags;
};
check_syscall_args(cloudabi_sys_sock_stat_get)

struct cloudabi64_sys_thread_create_args {
	syscallarg(cloudabi64_threadattr_t *) attr;
};
check_syscall_args(cloudabi64_sys_thread_create)

struct cloudabi_sys_thread_exit_args {
	syscallarg(cloudabi_lock_t *) lock;
};
check_syscall_args(cloudabi_sys_thread_exit)

struct cloudabi64_sys_thread_tcb_set_args {
	syscallarg(void *) tcb;
};
check_syscall_args(cloudabi64_sys_thread_tcb_set)

/*
 * System call prototypes.
 */

int	cloudabi_sys_clock_res_get(struct lwp *, const struct cloudabi_sys_clock_res_get_args *, register_t *);

int	cloudabi_sys_clock_time_get(struct lwp *, const struct cloudabi_sys_clock_time_get_args *, register_t *);

int	cloudabi_sys_condvar_signal(struct lwp *, const struct cloudabi_sys_condvar_signal_args *, register_t *);

int	cloudabi_sys_fd_close(struct lwp *, const struct cloudabi_sys_fd_close_args *, register_t *);

int	cloudabi_sys_fd_create1(struct lwp *, const struct cloudabi_sys_fd_create1_args *, register_t *);

int	cloudabi_sys_fd_create2(struct lwp *, const struct cloudabi_sys_fd_create2_args *, register_t *);

int	cloudabi_sys_fd_datasync(struct lwp *, const struct cloudabi_sys_fd_datasync_args *, register_t *);

int	cloudabi_sys_fd_dup(struct lwp *, const struct cloudabi_sys_fd_dup_args *, register_t *);

int	cloudabi64_sys_fd_pread(struct lwp *, const struct cloudabi64_sys_fd_pread_args *, register_t *);

int	cloudabi64_sys_fd_pwrite(struct lwp *, const struct cloudabi64_sys_fd_pwrite_args *, register_t *);

int	cloudabi64_sys_fd_read(struct lwp *, const struct cloudabi64_sys_fd_read_args *, register_t *);

int	cloudabi_sys_fd_replace(struct lwp *, const struct cloudabi_sys_fd_replace_args *, register_t *);

int	cloudabi_sys_fd_seek(struct lwp *, const struct cloudabi_sys_fd_seek_args *, register_t *);

int	cloudabi_sys_fd_stat_get(struct lwp *, const struct cloudabi_sys_fd_stat_get_args *, register_t *);

int	cloudabi_sys_fd_stat_put(struct lwp *, const struct cloudabi_sys_fd_stat_put_args *, register_t *);

int	cloudabi_sys_fd_sync(struct lwp *, const struct cloudabi_sys_fd_sync_args *, register_t *);

int	cloudabi64_sys_fd_write(struct lwp *, const struct cloudabi64_sys_fd_write_args *, register_t *);

int	cloudabi_sys_file_advise(struct lwp *, const struct cloudabi_sys_file_advise_args *, register_t *);

int	cloudabi_sys_file_allocate(struct lwp *, const struct cloudabi_sys_file_allocate_args *, register_t *);

int	cloudabi_sys_file_create(struct lwp *, const struct cloudabi_sys_file_create_args *, register_t *);

int	cloudabi_sys_file_link(struct lwp *, const struct cloudabi_sys_file_link_args *, register_t *);

int	cloudabi_sys_file_open(struct lwp *, const struct cloudabi_sys_file_open_args *, register_t *);

int	cloudabi_sys_file_readdir(struct lwp *, const struct cloudabi_sys_file_readdir_args *, register_t *);

int	cloudabi_sys_file_readlink(struct lwp *, const struct cloudabi_sys_file_readlink_args *, register_t *);

int	cloudabi_sys_file_rename(struct lwp *, const struct cloudabi_sys_file_rename_args *, register_t *);

int	cloudabi_sys_file_stat_fget(struct lwp *, const struct cloudabi_sys_file_stat_fget_args *, register_t *);

int	cloudabi_sys_file_stat_fput(struct lwp *, const struct cloudabi_sys_file_stat_fput_args *, register_t *);

int	cloudabi_sys_file_stat_get(struct lwp *, const struct cloudabi_sys_file_stat_get_args *, register_t *);

int	cloudabi_sys_file_stat_put(struct lwp *, const struct cloudabi_sys_file_stat_put_args *, register_t *);

int	cloudabi_sys_file_symlink(struct lwp *, const struct cloudabi_sys_file_symlink_args *, register_t *);

int	cloudabi_sys_file_unlink(struct lwp *, const struct cloudabi_sys_file_unlink_args *, register_t *);

int	cloudabi_sys_lock_unlock(struct lwp *, const struct cloudabi_sys_lock_unlock_args *, register_t *);

int	cloudabi_sys_mem_advise(struct lwp *, const struct cloudabi_sys_mem_advise_args *, register_t *);

int	cloudabi_sys_mem_lock(struct lwp *, const struct cloudabi_sys_mem_lock_args *, register_t *);

int	cloudabi_sys_mem_map(struct lwp *, const struct cloudabi_sys_mem_map_args *, register_t *);

int	cloudabi_sys_mem_protect(struct lwp *, const struct cloudabi_sys_mem_protect_args *, register_t *);

int	cloudabi_sys_mem_sync(struct lwp *, const struct cloudabi_sys_mem_sync_args *, register_t *);

int	cloudabi_sys_mem_unlock(struct lwp *, const struct cloudabi_sys_mem_unlock_args *, register_t *);

int	cloudabi_sys_mem_unmap(struct lwp *, const struct cloudabi_sys_mem_unmap_args *, register_t *);

int	cloudabi64_sys_poll(struct lwp *, const struct cloudabi64_sys_poll_args *, register_t *);

int	cloudabi64_sys_proc_exec(struct lwp *, const struct cloudabi64_sys_proc_exec_args *, register_t *);

int	cloudabi_sys_proc_exit(struct lwp *, const struct cloudabi_sys_proc_exit_args *, register_t *);

int	cloudabi64_sys_proc_fork(struct lwp *, const void *, register_t *);

int	cloudabi_sys_proc_raise(struct lwp *, const struct cloudabi_sys_proc_raise_args *, register_t *);

int	cloudabi_sys_random_get(struct lwp *, const struct cloudabi_sys_random_get_args *, register_t *);

int	cloudabi_sys_sock_accept(struct lwp *, const struct cloudabi_sys_sock_accept_args *, register_t *);

int	cloudabi_sys_sock_bind(struct lwp *, const struct cloudabi_sys_sock_bind_args *, register_t *);

int	cloudabi_sys_sock_connect(struct lwp *, const struct cloudabi_sys_sock_connect_args *, register_t *);

int	cloudabi_sys_sock_listen(struct lwp *, const struct cloudabi_sys_sock_listen_args *, register_t *);

int	cloudabi64_sys_sock_recv(struct lwp *, const struct cloudabi64_sys_sock_recv_args *, register_t *);

int	cloudabi64_sys_sock_send(struct lwp *, const struct cloudabi64_sys_sock_send_args *, register_t *);

int	cloudabi_sys_sock_shutdown(struct lwp *, const struct cloudabi_sys_sock_shutdown_args *, register_t *);

int	cloudabi_sys_sock_stat_get(struct lwp *, const struct cloudabi_sys_sock_stat_get_args *, register_t *);

int	cloudabi64_sys_thread_create(struct lwp *, const struct cloudabi64_sys_thread_create_args *, register_t *);

int	cloudabi_sys_thread_exit(struct lwp *, const struct cloudabi_sys_thread_exit_args *, register_t *);

int	cloudabi64_sys_thread_tcb_set(struct lwp *, const struct cloudabi64_sys_thread_tcb_set_args *, register_t *);

int	cloudabi_sys_thread_yield(struct lwp *, const void *, register_t *);

#endif /* _CLOUDABI64_SYS_SYSCALLARGS_H_ */
